### ISSUE TITLE
Inner Exception

### ISSUE THREAD

**Issue by Tameshiwari** [edx-labs/cosmos-graph-data#1]
Hi Sydney,

This may not be a real issue but a bit more a fine tuning explanation 
When running the **TechRecruiting.DataGeneration** console app prompt request ...the first request asks us to provide **StorageConnectionString** 
though no real specific info has been provided in that effect.

I had created a new **Azure Cosmos DB Graph API** and gathered all **URL, PRIMARY KEY and PRIMARY CONNECTION STRING**... 

I then tried to add a static **StorageConnectionString** key/value parameter in **App.Config** as followed 
`<appSettings>
    <add key="StorageContainerName" value="recruitingimages" />
    <add key="CosmosDatabaseName" value="ContosoRecruiting" />
    <add key="CosmosGraphName" value="RecruitingGraph" />
    <add key="StorageConnectionString" value="AccountEndpoint=https://myaccount.documents.azure.com:443/;AccountKey=AbCDE...k0lmN0pKres==;"/>
  </appSettings>`

Then added following in **Progam.cs** 
`string DEFAULT_STORAGE_CONNECTION_STRING = ConfigurationManager.AppSettings["StorageConnectionString"];`

and pass static **StorageConnectionString** 

`string StorageConnectionString = Prompt.Ask<string>("What is your Storage Account's connection string?", DEFAULT_STORAGE_CONNECTION_STRING);`

though ended up with 

**Inner Exception 1:
FormatException: No valid combination of account information found.**

Any information on how to overcome that and get a properly formatted string syntax sample would be appreciated. Thank you!

**Comment by seesharprun** [comment]
Thanks for reaching out! I'm actually surprised that someone was able to find this repository as it's based on a prototype project that hasn't been released to edX yet.

The https://github.com/edx-labs/cosmos-sql lab is the only one released right now.

The first prompt for the **StorageConnectionString** is referring to a connection string from an **Azure Storage** account instance. This data generation project requires both an Azure Cosmos DB account and Azure Storage account. The profile pictures are uploaded to Azure Storage while the actual user records (for the graph) are uploaded to Azure Cosmos DB.

So you simply need to create a Storage Account, go to the **Keys** section and record the connection string for the storage account.

Does that clear things up?

**Comment by Tameshiwari** [comment]
Thanks for your prompt response. Indeed your infos cleared things up and made a bit more sense.
I created **Azure Storage Account** prior to simply creating **Azure Cosmos DB Graph API** and confirmed the whole process worked on my side so we may close the issue. 
I then simply had to modify **Web.config** in **cosmos-graph-web** and got
results as I expected. I understand this is a starting prototype. **Recruiters**
**View** folder was blank but hey... that's fine with me as I'm sure
I can handle dealing with the rest at this stage. 

Now to answer your question regarding how I found those labs. I had first
enrolled in **EDX Azure Cosmos DB** session which I successfully completed.  I was looking for more advanced demos on **Github** and stumbled on those 3 demos.
I also had previously explored  a nice one  **cosmosdb-gremlin-flights** by **Anthony Chu** https://github.com/anthonychu/cosmosdb-gremlin-flights which actually uses live service datas.
 
Overall what I found interesting about the **cosmos-graph-data|cosmos-graph-web** demos is that they go a step above simply explaining how to create basic graph **Vertex** & **Edges** through **Azure
Portal Cosmos DB Graph API** blade. They correspond to a closer reality, that is - being able to manage those mainly through code combining **Gremlin** syntax.

I've also been exploring a couple of nice playground demos built in **Angular 5** and **d3.js** which were configured to run with **Gremlin Server** though one of my main interest now is to adapt those with **Azure Cosmos DB Graph API**. context. **Visual Studio Code**, **Azure Pack** **Cosmos DB** and **dotnet cli** is also a nice combination option I'm seriously exploring.

Thanks for sharing your infos, it's appreciated.
**Denys Chamberland @MawashiKid - Tameshiwari**

**Comment by seesharprun** [comment]
That’s great!

This repo will be renamed to **cosmos-graph** soon and the demo will be reworked and added to the edX course.

I will also ping you on GitHub if I see some more cosmos demoes.

**Comment by Tameshiwari** [comment]
Cool! Thanks :)
